[platformio]
default_envs = nano33ble_sense_original

[env:nano33ble_sense_original]
platform = nordicnrf52
board = nano33ble
framework = arduino
monitor_speed = 115200
lib_deps =
  arduino-libraries/Arduino_LSM9DS1
  arduino-libraries/Arduino_APDS9960
  arduino-libraries/Arduino_HTS221
  arduino-libraries/Arduino_LPS22HB
build_flags =
  -D BENCH_PROTOCOL_VERSION=1
