[platformio]
default_envs = xiao_esp32s3_sense

[env:xiao_esp32s3_sense]
platform = espressif32@6.12.0
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.partitions = huge_app.csv
build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D CORE_DEBUG_LEVEL=1
lib_deps =
  h2zero/NimBLE-Arduino@^2.3.7
